# Bu dosya otomatik olarak oluşturulmuştur (Dinamik Blacklist)
CORE_BLACKLIST = [
    "exploit bul",
    "crackeding",
    "dolandır açığı",
    "yoksay card",
    "suçer",
    "queryed",
    "fidye bul",
    "ransomware kodu",
    "system dos",
    "gizli ssn",
    "system_prompt wireshark",
    "select nasıl",
    "bypasss",
    "instructions ransomware",
    "database ransomware",
    "nasıl kartı",
    "shell delete",
    "nmap taktiği",
    "hack injection",
    "revoke exploit",
    "yoksay hack",
    "grant csrf",
    "fidyeing",
    "rolü vulnerability",
    "ssning",
    "botnet select",
    "sistemi ssn",
    "system açığı",
    "delete botnet",
    "porter",
    "gizli sömürü",
    "sql shell",
    "trojan açığı",
    "card grant",
    "insert dos",
    "update ddos",
    "nmap grant",
    "insert yaz",
    "information_schema botnet",
    "vulnerability taktiği",
    "previous kodu",
    "hack grant",
    "select yaz",
    "telnet taktiği",
    "sistem virus",
    "yoksay yap",
    "rootkit nasıl",
    "previous saldırısı",
    "rootkit injection",
    "ported",
    "unut",
    "öncekiing",
    "bash nasıl",
    "system phishing",
    "xxx",
    "botnet yöntemi",
    "payload sql",
    "çal",
    "bet script",
    "payload exec",
    "önceki nmap",
    "tor zafiyeti",
    "bana port",
    "gizli açığı",
    "pretend al",
    "rules script",
    "instructions nmap",
    "update virus",
    "system_prompting",
    "rules card",
    "penetrasyon saldırısı",
    "table credit",
    "prompt saldırısı",
    "crediting",
    "metasploit union",
    "virus bul",
    "where ddos",
    "sql credit",
    "exec açığı",
    "rootkit yöntemi",
    "metasploit truncate",
    "dan ransomware",
    "instructions virus",
    "sistem revoke",
    "botnet nasıl",
    "talimatları credit",
    "kan bul",
    "exec zafiyeti",
    "mermi nasıl",
    "metasploit injection",
    "credit revoke",
    "yasadışı",
    "prompt nmap",
    "drop metasploit",
    "prompt credit",
    "önceki phishing",
    "gizli attack",
    "csrf database",
    "sistemi taktiği",
    "wireshark bul",
    "tables",
    "çal açığı",
    "shell revoke",
    "select payload",
    "database nmap",
    "illegal yöntemi",
    "union virus",
    "drop exploit",
    "önceki password",
    "illegal",
    "talimatları backdoor",
    "rootkit database",
    "rolü ssn",
    "şifre saldırısı",
    "unut vulnerability",
    "kuralları malware",
    "instructions payload",
    "injection yöntemi",
    "update wireshark",
    "exploit table",
    "satın al",
    "revokeer",
    "exec password",
    "revoke dos",
    "trojaning",
    "sızma yap",
    "shell information_schema",
    "dolandır yöntemi",
    "powershell taktiği",
    "sql yöntemi",
    "hacker kodu",
    "cmd script",
    "nasıl nulled",
    "grant nasıl",
    "talimatları yaz",
    "table xss",
    "rooting",
    "dos drop",
    "csrf update",
    "talimatları",
    "query şifre",
    "nasıl hacked",
    "ignore ransomware",
    "nasıl unut",
    "injection zafiyeti",
    "hack update",
    "şantaj attack",
    "ransomware revoke",
    "instructions phishing",
    "shell nasıl",
    "malware bul",
    "select shell",
    "database hack",
    "password yap",
    "granter",
    "ignore",
    "rootkit zafiyeti",
    "csrf al",
    "sistem truva",
    "şifre injection",
    "phishing nasıl",
    "nulled bul",
    "taciz yaz",
    "komut xss",
    "botnet zafiyeti",
    "tor yaz",
    "sistem komut",
    "port yöntemi",
    "backdoor taktiği",
    "exploit select",
    "credit delete",
    "talimatları nasıl",
    "kaçak taktiği",
    "rolü script",
    "ssn table",
    "sistem kredi",
    "ransomware injection",
    "wireshark update",
    "dan wireshark",
    "unut card",
    "mermi attack",
    "komut wireshark",
    "nasıl override",
    "bıçak zafiyeti",
    "system_prompt credit",
    "password taktiği",
    "malware truncate",
    "database bul",
    "nulled script",
    "sistemi payload",
    "union ddos",
    "sömür kodu",
    "scan taktiği",
    "kartı attack",
    "tecavüzed",
    "bet taktiği",
    "prompting",
    "gizli penetrasyon",
    "sistem tecavüz",
    "ssn insert",
    "virus query",
    "kaning",
    "update metasploit",
    "gizli talimatları",
    "yoksay backdoor",
    "pretend trojan",
    "rootkit grant",
    "deleteed",
    "gizli bypass",
    "silahing",
    "system password",
    "kredi bul",
    "tor attack",
    "kuralları nasıl",
    "roleplay backdoor",
    "vulnerabilityed",
    "çalmak açığı",
    "query al",
    "powershell script",
    "gizli kan",
    "instructions card",
    "system_prompt ddos",
    "alter backdoor",
    "ransomwares",
    "shell schema",
    "gizli kuralları",
    "öldür taktiği",
    "sızdırma nasıl",
    "ddos select",
    "pretend saldırısı",
    "shell zafiyeti",
    "nasıl nmap",
    "insert saldırısı",
    "information_schema hack",
    "sudo attack",
    "sheller",
    "database payload",
    "password saldırısı",
    "nulled taktiği",
    "vulnerabilitying",
    "alter credit",
    "xss drop",
    "kuralları shell",
    "dan payload",
    "wireshark information_schema",
    "komut saldırısı",
    "sızmas",
    "tecavüz script",
    "union backdoor",
    "delete nmap",
    "rolü metasploit",
    "xss attack",
    "yasadışıs",
    "şantajed",
    "nasıl tecavüz",
    "sshing",
    "roleplay yap",
    "gizli shell",
    "nulled zafiyeti",
    "database wireshark",
    "scan yöntemi",
    "sql exploit",
    "öldür al",
    "suç al",
    "porn",
    "alterer",
    "schema rootkit",
    "delete shell",
    "exec wireshark",
    "exec ransomware",
    "cmds",
    "rules nasıl",
    "gizli malware",
    "unut ransomware",
    "payloads",
    "exec virus",
    "bana gizli",
    "sistem satın",
    "exec phishing",
    "dan dos",
    "şantaj zafiyeti",
    "unut rootkit",
    "xxx saldırısı",
    "dolandır kodu",
    "system_prompt taktiği",
    "ifşa bul",
    "dan xss",
    "bypassla yöntemi",
    "rolü yaz",
    "kan saldırısı",
    "override rootkit",
    "schema kodu",
    "dos truncate",
    "şifre revoke",
    "payload injection",
    "update nasıl",
    "instructionsing",
    "darkweb",
    "root nasıl",
    "bypassla password",
    "bana instructions",
    "tableed",
    "daner",
    "cracked al",
    "hack revoke",
    "truncate bul",
    "instructions kodu",
    "vulnerability script",
    "önceki taktiği",
    "şantaj yaz",
    "saldırı yap",
    "hacked taktiği",
    "nasıl bet",
    "ruleser",
    "drop payload",
    "override xss",
    "önceki ssn",
    "table açığı",
    "yaped",
    "porn bul",
    "sistem system_prompt",
    "insert password",
    "silah nasıl",
    "backdoor sql",
    "schema csrf",
    "davran ssn",
    "system_prompt",
    "bana çal",
    "gizli açık",
    "sızdırma attack",
    "vulnerability al",
    "drop ransomware",
    "rules taktiği",
    "saldırı taktiği",
    "rules kodu",
    "bypassed zafiyeti",
    "shell attack",
    "penetrasyon yöntemi",
    "card yaz",
    "yap nasıl",
    "payload",
    "gizli şifre",
    "şantaj saldırısı",
    "yap kodu",
    "bana shell",
    "öncekis",
    "truncate credit",
    "revoke credit",
    "virus injection",
    "update botnet",
    "ssn taktiği",
    "kartı açığı",
    "sızdırma bul",
    "phishing script",
    "unut zafiyeti",
    "alter",
    "nasıl card",
    "bypassla card",
    "kaçaking",
    "kaçaked",
    "insert",
    "dolandır zafiyeti",
    "password update",
    "bomba attack",
    "instructions bul",
    "gizli bul",
    "kaçaks",
    "gizli illegal",
    "kumars",
    "backdoor schema",
    "table nmap",
    "botnets",
    "system rootkit",
    "gizli rolü",
    "intihar bul",
    "system backdoor",
    "override ssn",
    "saldırıing",
    "bana credit",
    "telneter",
    "bash yaz",
    "çalmaked",
    "delete payload",
    "alter trojan",
    "credit bul",
    "kimlik",
    "önceki dos",
    "viruss",
    "truncate password",
    "gizli hacker",
    "bıçak açığı",
    "sqler",
    "öldüred",
    "hacker nasıl",
    "hacker taktiği",
    "gizli insert",
    "nmap query",
    "leak zafiyeti",
    "backdoor exec",
    "bashs",
    "bypass bul",
    "ssn schema",
    "sistemi nmap",
    "rules botnet",
    "previous nmap",
    "exec yaz",
    "yap malware",
    "bypassla vulnerability",
    "bana delete",
    "sistem ftp",
    "bana kan",
    "xss where",
    "system nmap",
    "previous password",
    "kartı al",
    "database zafiyeti",
    "admin taktiği",
    "öldür",
    "satıned",
    "exec exploit",
    "override backdoor",
    "passwords",
    "table virus",
    "phishing schema",
    "nasıl union",
    "dos update",
    "metasploit select",
    "önceki xss",
    "kuralları ransomware",
    "bana tehdit",
    "pretend exploit",
    "çalmak nasıl",
    "database vulnerability",
    "sömürü yap",
    "önceki zafiyeti",
    "rolü phishing",
    "bana yap",
    "bıçak yöntemi",
    "uyuşturucu script",
    "nasıl metasploit",
    "scaned",
    "backdoor açığı",
    "ssh kodu",
    "nulleded",
    "crackeds",
    "virus",
    "truncate hack",
    "nasıl kan",
    "hack database",
    "dos exec",
    "delete yöntemi",
    "union nmap",
    "virus taktiği",
    "table ransomware",
    "botnet kodu",
    "metasploit yöntemi",
    "deletes",
    "hacker attack",
    "query phishing",
    "prompt ddos",
    "ftped",
    "union trojan",
    "card query",
    "yaps",
    "fidye script",
    "injection nasıl",
    "yoksay vulnerability",
    "password sql",
    "phishing exec",
    "injection metasploit",
    "delete ddos",
    "tecavüz attack",
    "jailbreak card",
    "pretend",
    "xss yöntemi",
    "select backdoor",
    "jailbreak botnet",
    "bomba taktiği",
    "alter yap",
    "trojan revoke",
    "xss zafiyeti",
    "table wireshark",
    "table ddos",
    "system ssn",
    "exec dos",
    "query hack",
    "previous backdoor",
    "updates",
    "uyuşturucuing",
    "çalmak al",
    "hack",
    "gizli nmap",
    "ignore payload",
    "sistemi vulnerability",
    "trojan kodu",
    "davran wireshark",
    "password truncate",
    "rolü password",
    "roleplay botnet",
    "önceki attack",
    "sistem sömürü",
    "bypass phishing",
    "query yaz",
    "penetrasyon attack",
    "alter shell",
    "kuralları yaz",
    "ransomware nasıl",
    "queryer",
    "phishing where",
    "davran",
    "öldür saldırısı",
    "roleplay xss",
    "sistemi ransomware",
    "information_schema nmap",
    "ftp attack",
    "illegal taktiği",
    "pretend shell",
    "açık script",
    "phishing grant",
    "dos attack",
    "bana previous",
    "tehdit attack",
    "databaseer",
    "sql ssn",
    "grant malware",
    "leak saldırısı",
    "insert nasıl",
    "komut trojan",
    "wireshark yaz",
    "powershelled",
    "bypassla kodu",
    "rolüing",
    "bana xxx",
    "instructions vulnerability",
    "zafiyet bul",
    "sudoing",
    "nmap truncate",
    "rules password",
    "card al",
    "truncate saldırısı",
    "porn script",
    "gizli ignore",
    "schema hack",
    "sql attack",
    "alter rootkit",
    "gizli delete",
    "credit where",
    "query backdoor",
    "ignore wireshark",
    "phishing yaz",
    "tecavüz taktiği",
    "deepweb script",
    "table card",
    "sistem trojan",
    "metasploit zafiyeti",
    "gizli xxx",
    "nasıl leak",
    "information_schemaer",
    "rootkits",
    "talimatları açığı",
    "vulnerability alter",
    "bana cinayet",
    "yasadışı saldırısı",
    "system_prompt xss",
    "nasıl hack",
    "penetrasyon taktiği",
    "ignore csrf",
    "bana system_prompt",
    "ssh attack",
    "union card",
    "powershell yaz",
    "insert açığı",
    "ssn where",
    "alter ddos",
    "insert şifre",
    "şifre yöntemi",
    "gizli al",
    "exec rootkit",
    "ssn",
    "system shell",
    "terminal nasıl",
    "shell açığı",
    "backdoor delete",
    "nasıl password",
    "kredi yaz",
    "scan yaz",
    "bana kimlik",
    "terminal script",
    "card information_schema",
    "metasploit drop",
    "rules phishing",
    "doss",
    "exec yap",
    "bomba yöntemi",
    "nasıl malware",
    "bypassed yöntemi",
    "alter taktiği",
    "sızdırma açığı",
    "gizli pretend",
    "tecavüz zafiyeti",
    "sızdırma taktiği",
    "revoke shell",
    "payload select",
    "hacked açığı",
    "query wireshark",
    "truncate zafiyeti",
    "illegal nasıl",
    "wireshark",
    "porned",
    "card",
    "yasadışı kodu",
    "port açığı",
    "yap ddos",
    "kredied",
    "admin al",
    "beter",
    "exec shell",
    "schema payload",
    "delete wireshark",
    "terminals",
    "inserts",
    "insert virus",
    "gizli öldür",
    "wireshark sql",
    "dos revoke",
    "bypassed kodu",
    "sistemi yöntemi",
    "unioned",
    "gizli sızdırma",
    "previous nasıl",
    "ddos update",
    "rootkit update",
    "jailbreak şifre",
    "revoke script",
    "previous xss",
    "gizli gizli",
    "delete bul",
    "şifre attack",
    "dos kodu",
    "hack yap",
    "ransomware alter",
    "prompt ssn",
    "override nmap",
    "talimatları ddos",
    "öldürs",
    "schema virus",
    "credit table",
    "union shell",
    "virus information_schema",
    "çalmak attack",
    "taciz nasıl",
    "truncate botnet",
    "xss script",
    "table yap",
    "bana deepweb",
    "gizli bypassla",
    "cinayet script",
    "exploit attack",
    "rolü payload",
    "cinayet açığı",
    "virus exec",
    "insert taktiği",
    "yasadışı attack",
    "porns",
    "ddos database",
    "wiresharking",
    "penetrasyon zafiyeti",
    "yasadışı script",
    "schema trojan",
    "union phishing",
    "xssed",
    "öldür zafiyeti",
    "cinayeter",
    "query script",
    "alter saldırısı",
    "update card",
    "taciz açığı",
    "illegal al",
    "bana penetrasyon",
    "kartı yaz",
    "previous zafiyeti",
    "payload script",
    "unut al",
    "hack taktiği",
    "query vulnerability",
    "system_prompt dos",
    "update payload",
    "update script",
    "system_prompt açığı",
    "csrf",
    "nmap script",
    "powershell yöntemi",
    "gizli saldırısı",
    "davraning",
    "alter malware",
    "grant trojan",
    "xss yaz",
    "sistem bypassla",
    "port yap",
    "backdoor union",
    "sistemi şifre",
    "trojans",
    "talimatları shell",
    "port kodu",
    "bypass ssn",
    "yap taktiği",
    "deepwebs",
    "çalmak script",
    "insert trojan",
    "roleplayed",
    "kartı script",
    "scans",
    "ssn update",
    "tehdit yap",
    "system_prompt virus",
    "jailbreak açığı",
    "sızma al",
    "drop malware",
    "suç açığı",
    "previous attack",
    "önceki açığı",
    "password",
    "gizli komut",
    "wireshark kodu",
    "nmap revoke",
    "ftp",
    "bypassed al",
    "wireshark drop",
    "information_schemaing",
    "bypassed taktiği",
    "nasıl gizli",
    "truncate wireshark",
    "unut exploit",
    "jailbreak saldırısı",
    "uyuşturucus",
    "system_prompt exploit",
    "virüs attack",
    "override ransomware",
    "talimatları password",
    "shell table",
    "açık yöntemi",
    "dolandır",
    "truncate açığı",
    "previous trojan",
    "revoke payload",
    "komut password",
    "nasıl kimlik",
    "silah zafiyeti",
    "şifre sql",
    "union vulnerability",
    "kuralları ssn",
    "yoksay saldırısı",
    "yoksay nasıl",
    "rootkit bul",
    "kuralları al",
    "suç script",
    "gizli injection",
    "ifşa script",
    "rolü zafiyeti",
    "bypass csrf",
    "exploit sql",
    "kuralları yap",
    "sistem hack",
    "bıçak attack",
    "virüs al",
    "sudos",
    "insert wireshark",
    "kredi taktiği",
    "delete metasploit",
    "where script",
    "override nasıl",
    "exploited",
    "xxx yöntemi",
    "bana kredi",
    "ftping",
    "davran saldırısı",
    "nmaping",
    "çalmak yöntemi",
    "davran kodu",
    "botnet al",
    "phishing injection",
    "select attack",
    "terminal attack",
    "nulled yap",
    "kimlik yap",
    "botnet",
    "backdoors",
    "bypass taktiği",
    "gizli kredi",
    "mermi taktiği",
    "sistem nulled",
    "bana sistemi",
    "credit update",
    "önceki wireshark",
    "nmap sql",
    "kuralları metasploit",
    "unions",
    "ignoreed",
    "schema card",
    "sömürü nasıl",
    "komuted",
    "rolüs",
    "talimatları virus",
    "trojan database",
    "wireshark schema",
    "sömürü al",
    "nasıl komut",
    "select zafiyeti",
    "delete zafiyeti",
    "ddos attack",
    "csrf kodu",
    "illegal yaz",
    "davran attack",
    "bypassed bul",
    "ssns",
    "nasıl shell",
    "droping",
    "darkweb attack",
    "bana bet",
    "where hack",
    "database açığı",
    "table backdoor",
    "saldırı açığı",
    "port taktiği",
    "truva al",
    "darkweb taktiği",
    "ddos bul",
    "unut virus",
    "nasıl grant",
    "cmd kodu",
    "komut kodu",
    "select trojan",
    "yasadışıer",
    "drop phishing",
    "metasploit update",
    "database metasploit",
    "botnet attack",
    "sistem csrf",
    "yoksay rootkit",
    "cmder",
    "malware update",
    "information_schema ransomware",
    "leaked",
    "backdoor where",
    "prompt şifre",
    "backdoor yap",
    "shell alter",
    "rules metasploit",
    "cinayet attack",
    "update malware",
    "select ransomware",
    "intihar kodu",
    "cmd taktiği",
    "yap yap",
    "illegal bul",
    "sızdırma kodu",
    "bana phishing",
    "password delete",
    "system_prompt al",
    "dos yap",
    "instructions ddos",
    "insert nmap",
    "zafiyet yöntemi",
    "komut shell",
    "komut exploit",
    "ftp zafiyeti",
    "credit kodu",
    "kumar script",
    "ignore xss",
    "ssh zafiyeti",
    "nasıl kuralları",
    "sqled",
    "jailbreaks",
    "sistem talimatları",
    "bypass yaz",
    "pretend yaz",
    "bash bul",
    "ssn nasıl",
    "where bul",
    "talimatları ssn",
    "malware delete",
    "information_schema backdoor",
    "unut taktiği",
    "ignore shell",
    "kuralları password",
    "dan",
    "suç yap",
    "query card",
    "information_schema xss",
    "roleplay bul",
    "ddos insert",
    "botnet schema",
    "saldırı saldırısı",
    "roleplay trojan",
    "kumar yap",
    "drop csrf",
    "rooter",
    "xss truncate",
    "schemaing",
    "nasıl xss",
    "revoke card",
    "union password",
    "kurallarıs",
    "bypasseds",
    "malware injection",
    "backdoor bul",
    "deepweb nasıl",
    "credit injection",
    "bypassla saldırısı",
    "zafiyet yaz",
    "hacker al",
    "satın yap",
    "information_schema payload",
    "sistem credit",
    "sistem union",
    "card database",
    "databases",
    "sistemied",
    "sql trojan",
    "nasıl fidye",
    "sql",
    "grant",
    "information_schema credit",
    "injection ransomware",
    "sistemi metasploit",
    "taciz zafiyeti",
    "rules açığı",
    "trojan union",
    "tehdit açığı",
    "bana ignore",
    "sızma saldırısı",
    "vulnerability where",
    "prompt rootkit",
    "dos select",
    "bypassla virus",
    "credit select",
    "bomba yap",
    "çal yaz",
    "selects",
    "virüs zafiyeti",
    "grant card",
    "password yaz",
    "metasploit database",
    "malware al",
    "nmap delete",
    "sistemi password",
    "önceki yap",
    "grant yöntemi",
    "phishing kodu",
    "dan yap",
    "zafiyet yap",
    "cinayet kodu",
    "taciz bul",
    "ftp script",
    "query botnet",
    "darkweb açığı",
    "pretend bul",
    "nasıl ifşa",
    "card attack",
    "nasıl şantaj",
    "nasıl bomba",
    "injection",
    "database al",
    "sistemi yap",
    "database şifre",
    "select saldırısı",
    "dos nasıl",
    "açık bul",
    "table al",
    "unut malware",
    "gizli xss",
    "database backdoor",
    "nasıl yap",
    "malware attack",
    "terminal açığı",
    "previous malware",
    "sistem wireshark",
    "sızmaed",
    "yoksay ransomware",
    "powershell bul",
    "hacked nasıl",
    "insert xss",
    "yap wireshark",
    "admin saldırısı",
    "ransomware update",
    "sızma kodu",
    "talimatlarıer",
    "önceki nasıl",
    "torer",
    "select virus",
    "prompt payload",
    "bana ransomware",
    "jailbreak csrf",
    "update",
    "talimatlarıs",
    "kan script",
    "previous rootkit",
    "fidyeed",
    "deepweb yöntemi",
    "ftp yap",
    "previous credit",
    "botneted",
    "bombaer",
    "prompt taktiği",
    "tor yap",
    "unut bul",
    "sistem dan",
    "trojan select",
    "malwareing",
    "intihared",
    "sql script",
    "gizli zafiyeti",
    "credit information_schema",
    "sql zafiyeti",
    "darkweb saldırısı",
    "password al",
    "tacizing",
    "ifşa saldırısı",
    "ssner",
    "trojan nasıl",
    "roleplay taktiği",
    "bash taktiği",
    "phishing taktiği",
    "virus select",
    "rolü ddos",
    "sistem darkweb",
    "override vulnerability",
    "bana jailbreak",
    "update kodu",
    "unut kodu",
    "update hack",
    "gizli prompt",
    "yap al",
    "bomba yaz",
    "ddoss",
    "şifre al",
    "database shell",
    "rolü hack",
    "kumar bul",
    "jailbreak wireshark",
    "jailbreak ransomware",
    "shell drop",
    "önceki şifre",
    "gizli system_prompt",
    "intihar taktiği",
    "gizli kaçak",
    "illegal attack",
    "bana table",
    "gizli tor",
    "porn zafiyeti",
]
